### ISSUE TITLE
Setup Missing

### ISSUE THREAD

**Issue by zzj0402** [janetlauyeung/crossGENRE4RST#1]
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/15345547/236745422-ce8d735b-b97b-44df-8f8e-d70812bd2ca6.png">

**Comment by janetlauyeung** [comment]
Hi there, 

Thanks for your interest and reporting the missing file. The original repository for this step can be found [here](https://github.com/grig-guz/ubc-coref), but I have also updated this repository as well. This step is not very necessary or relevant if one is not trying to use the coref modules that come with the original implementation. This was included for completeness purposes. 

Please let me know if you encounter further problem. 


Best,
Janet
